/**
 * @file ui_fonts.h
 * Font declarations.
 *
 * GENERATED by tools/fonts/generate_fonts.py - DO NOT EDIT.
 *
 * Text faces: Barlow Semi Condensed / Barlow Condensed (SIL OFL 1.1).
 * Icons: Material Design Icons (Apache-2.0).
 */
#pragma once

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(ui_font_12)       /* BarlowSemiCondensed-Medium 12px, icons */
LV_FONT_DECLARE(ui_font_14)       /* BarlowSemiCondensed-Medium 14px, icons */
LV_FONT_DECLARE(ui_font_16)       /* BarlowSemiCondensed-SemiBold 16px, icons */
LV_FONT_DECLARE(ui_font_20)       /* BarlowSemiCondensed-SemiBold 20px, icons */
LV_FONT_DECLARE(ui_font_28)       /* BarlowSemiCondensed-SemiBold 28px */
LV_FONT_DECLARE(ui_font_speed)    /* BarlowCondensed-SemiBold 64px digits */
LV_FONT_DECLARE(ui_icons_24)      /* icons */
LV_FONT_DECLARE(ui_icons_48)      /* large icons */

#ifdef __cplusplus
}
#endif
