/**
 * @file ui_icons.h
 * Icon glyphs (Material Design Icons, Apache-2.0) mapped to the private use area.
 *
 * GENERATED by tools/fonts/generate_fonts.py - DO NOT EDIT.
 *
 * Icons are available in ui_font_12/14/16/20 (inline with text) and in
 * ui_icons_24. A subset is available in ui_icons_48 (see ICON_LARGE_*).
 */
#pragma once

#define ICON_DASHBOARD        "\xEE\x80\x80"  /* U+E000 mdi-speedometer */
#define ICON_LIVE             "\xEE\x80\x81"  /* U+E001 mdi-chart-line */
#define ICON_DIAG             "\xEE\x80\x82"  /* U+E002 mdi-car-wrench */
#define ICON_TRIP             "\xEE\x80\x83"  /* U+E003 mdi-map-marker-distance */
#define ICON_SETTINGS         "\xEE\x80\x84"  /* U+E004 mdi-cog */
#define ICON_ENGINE           "\xEE\x80\x85"  /* U+E005 mdi-engine */
#define ICON_COOLANT          "\xEE\x80\x86"  /* U+E006 mdi-coolant-temperature */
#define ICON_OIL_TEMP         "\xEE\x80\x87"  /* U+E007 mdi-oil-temperature */
#define ICON_BATTERY          "\xEE\x80\x88"  /* U+E008 mdi-car-battery */
#define ICON_FUEL             "\xEE\x80\x89"  /* U+E009 mdi-gas-station */
#define ICON_FUEL_RATE        "\xEE\x80\x8A"  /* U+E00A mdi-fuel */
#define ICON_THERMOMETER      "\xEE\x80\x8B"  /* U+E00B mdi-thermometer */
#define ICON_AIR              "\xEE\x80\x8C"  /* U+E00C mdi-weather-windy */
#define ICON_GAUGE            "\xEE\x80\x8D"  /* U+E00D mdi-gauge */
#define ICON_GAUGE_LOW        "\xEE\x80\x8E"  /* U+E00E mdi-gauge-low */
#define ICON_SPEED            "\xEE\x80\x8F"  /* U+E00F mdi-speedometer-medium */
#define ICON_THROTTLE         "\xEE\x80\x90"  /* U+E010 mdi-valve */
#define ICON_TURBO            "\xEE\x80\x91"  /* U+E011 mdi-car-turbocharger */
#define ICON_TIMING           "\xEE\x80\x92"  /* U+E012 mdi-angle-acute */
#define ICON_TRIM             "\xEE\x80\x93"  /* U+E013 mdi-tune-vertical */
#define ICON_PISTON           "\xEE\x80\x94"  /* U+E014 mdi-piston */
#define ICON_SHIFT            "\xEE\x80\x95"  /* U+E015 mdi-car-shift-pattern */
#define ICON_SPEED_LIMIT      "\xEE\x80\x96"  /* U+E016 mdi-car-speed-limiter */
#define ICON_FLASH            "\xEE\x80\x97"  /* U+E017 mdi-lightning-bolt */
#define ICON_CAR              "\xEE\x80\x98"  /* U+E018 mdi-car */
#define ICON_CAR_INFO         "\xEE\x80\x99"  /* U+E019 mdi-car-info */
#define ICON_ROAD             "\xEE\x80\x9A"  /* U+E01A mdi-road-variant */
#define ICON_TIMER            "\xEE\x80\x9B"  /* U+E01B mdi-timer-outline */
#define ICON_STOPWATCH        "\xEE\x80\x9C"  /* U+E01C mdi-timer */
#define ICON_HISTORY          "\xEE\x80\x9D"  /* U+E01D mdi-history */
#define ICON_SIGMA            "\xEE\x80\x9E"  /* U+E01E mdi-sigma */
#define ICON_ARROW_UP         "\xEE\x80\x9F"  /* U+E01F mdi-arrow-up-bold */
#define ICON_ALERT            "\xEE\x80\xA0"  /* U+E020 mdi-alert */
#define ICON_ALERT_CIRCLE     "\xEE\x80\xA1"  /* U+E021 mdi-alert-circle */
#define ICON_INFO             "\xEE\x80\xA2"  /* U+E022 mdi-information-outline */
#define ICON_CHECK_CIRCLE     "\xEE\x80\xA3"  /* U+E023 mdi-check-circle */
#define ICON_CHECK            "\xEE\x80\xA4"  /* U+E024 mdi-check */
#define ICON_CLOSE            "\xEE\x80\xA5"  /* U+E025 mdi-close */
#define ICON_CHEVRON_RIGHT    "\xEE\x80\xA6"  /* U+E026 mdi-chevron-right */
#define ICON_BACK             "\xEE\x80\xA7"  /* U+E027 mdi-arrow-left */
#define ICON_PLUS             "\xEE\x80\xA8"  /* U+E028 mdi-plus */
#define ICON_MINUS            "\xEE\x80\xA9"  /* U+E029 mdi-minus */
#define ICON_LINK             "\xEE\x80\xAA"  /* U+E02A mdi-lan-connect */
#define ICON_LINK_OFF         "\xEE\x80\xAB"  /* U+E02B mdi-lan-disconnect */
#define ICON_VIEW_GRID        "\xEE\x80\xAC"  /* U+E02C mdi-view-grid-outline */
#define ICON_VIEW_DASH        "\xEE\x80\xAD"  /* U+E02D mdi-view-dashboard-outline */
#define ICON_SCAN             "\xEE\x80\xAE"  /* U+E02E mdi-magnify */
#define ICON_DELETE           "\xEE\x80\xAF"  /* U+E02F mdi-trash-can-outline */
#define ICON_RESTORE          "\xEE\x80\xB0"  /* U+E030 mdi-restore */
#define ICON_RESTART          "\xEE\x80\xB1"  /* U+E031 mdi-restart */
#define ICON_BRIGHTNESS       "\xEE\x80\xB2"  /* U+E032 mdi-brightness-6 */
#define ICON_BRIGHTNESS_AUTO  "\xEE\x80\xB3"  /* U+E033 mdi-brightness-auto */
#define ICON_SUN              "\xEE\x80\xB4"  /* U+E034 mdi-white-balance-sunny */
#define ICON_NIGHT            "\xEE\x80\xB5"  /* U+E035 mdi-weather-night */
#define ICON_ROTATE           "\xEE\x80\xB6"  /* U+E036 mdi-screen-rotation */
#define ICON_PALETTE          "\xEE\x80\xB7"  /* U+E037 mdi-palette */
#define ICON_RULER            "\xEE\x80\xB8"  /* U+E038 mdi-ruler */
#define ICON_BELL             "\xEE\x80\xB9"  /* U+E039 mdi-bell-ring */
#define ICON_VOLUME           "\xEE\x80\xBA"  /* U+E03A mdi-volume-high */
#define ICON_LED              "\xEE\x80\xBB"  /* U+E03B mdi-led-on */
#define ICON_TOUCH            "\xEE\x80\xBC"  /* U+E03C mdi-gesture-tap */
#define ICON_TARGET           "\xEE\x80\xBD"  /* U+E03D mdi-crosshairs */
#define ICON_LANGUAGE         "\xEE\x80\xBE"  /* U+E03E mdi-translate */
#define ICON_CHIP             "\xEE\x80\xBF"  /* U+E03F mdi-chip */
#define ICON_MEMORY           "\xEE\x81\x80"  /* U+E040 mdi-memory */
#define ICON_DATABASE         "\xEE\x81\x81"  /* U+E041 mdi-database */
